Feature/mirror service
sahibamittal/dependency-track pull request #63
Opened 2023-01-11 00:58 UTC by japurva1502

### Description

### Addressed Issue

### Additional Details

### Checklist

- [ ] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

2023-01-11 09:18 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +            LOGGER.debug("Synchronizing Google OSV advisory: " + record.key());
This will be logged for other datasource as well like NVD mirrored vulnerability. So, may be change it to 
LOGGER.debug("Synchronizing mirrored vulnerability: " + record.key());

2023-01-11 09:43 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +        if (cycloneVuln.getReferences() != null && cycloneVuln.getReferences().size() > 0) {
Field references in cycloneDx vulnerability (`cycloneVuln.getReferences()`) contains aliases. 
Need to change mapping here.
`cycloneVuln.getAdvisories()` as well as `bom.getExternalReferences()` contain the info on vulnerability references links.

2023-01-11 09:53 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +                final Cwe cwe = CweResolver.getInstance().resolve(qm, cycloneVuln.getCwes().get(i).toString());
`cycloneVuln.getCwes()` contains CWEs integer values (ex. 315 instead of CWE-315). 
`
public Cwe resolve(final QueryManager qm, final String cweString) {
        final Integer cweId = parseCweString(cweString);
        return (cweId != null) ? qm.getCweById(cweId) : null;
    }
`
Possible Solutions:
1. Either pass prefixed string value:
`final Cwe cwe = CweResolver.getInstance().resolve(qm, "CWE-"+cycloneVuln.getCwes().get(i).toString());`
2. OR better, remove the resolver use completely:
`final Cwe cwe = qm.getCweById(cweId);`

2023-01-11 09:58 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +            vuln.setCvssV2Vector(cycloneVuln.getRatings().get(0).getVector());
For both CVSSv2/3, also set score values as well:
```
vuln.setCvssV2BaseScore(cycloneVuln.getRatings().get(0).getScore());
vuln.setCvssV3BaseScore(cycloneVuln.getRatings().get(0).getScore());
```

2023-01-11 10:03 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +//        }
Remove comments, not needed. We have score/vector in bom for v2/v3.

2023-01-11 11:38 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +        if (affectedPackage.getComponents().get(0).getPurl() == null) {
For each affected package, there is a bomRef which maps to a component in components list.
Use the bomRef to get the correct component purl.

Instead of Bom object, may be pass the associated (with same bomRef id) component and affected package objects in parameters.

2023-01-11 11:43 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +        if (range.contains(",")) {
Follow the range specifier format to break down the range string.
https://github.com/package-url/purl-spec/blob/version-range-spec/VERSION-RANGE-SPEC.rst#version-range-specifier

**Format:** vers:<versioning-scheme>/<version-constraint>|<version-constraint>|...
**Example**: vers:npm/1.2.3|>=2.0.0|<5.0.0

2023-01-11 11:46 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +        vuln.setDescription(cycloneVuln.getDescription());
`vuln.setDescription(cycloneVuln.getDetail());`

2023-01-13 15:26 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +        for ( Component component : affectedPackage.getComponents()){
need check for null and empty list to avoid NPE before for loop

2023-01-13 15:32 UTC, sahibamittal approved these changes
LGTM 👍🏼

2023-01-17 12:06 UTC, nscuro requested changes
Some changes I'd like to see. Also, please remove the `.DS_Store` files.

2023-01-17 12:06 UTC, nscuro commented on src/test/java/org/dependencytrack/event/kafka/CycloneDxToDTSchemaParserTest.java
> +    }
These checks could all be done in `testVulnParsing`.

2023-01-17 12:06 UTC, nscuro commented on src/test/java/org/dependencytrack/event/kafka/CycloneDxToDTSchemaParserTest.java
> +
There should be tests for the processor itself, see https://kafka.apache.org/33/documentation/streams/developer-guide/testing.html#unit-testing-processors or https://github.com/mehab/DTKafkaPOC/blob/main/vulnerability-analyzer/src/test/java/org/acme/processor/snyk/SnykProcessorTest.java if you need inspiration.

Persisting vulnerabilities to the database is one of the processor's primary jobs, so that aspect should be tested, too. Instead of only testing individual parsing methods, try to verify that what is persisted to the DB is correct.

2023-01-24 15:28 UTC, sahibamittal commented on src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
> +            default -> Vulnerability.Source.OSV;
I'll fix this.

2023-01-25 16:25 UTC, nscuro approved these changes
![image](https://user-images.githubusercontent.com/5693141/214619170-5ba81c37-3c13-4625-ab5f-d653d73e4247.png)

2023-01-25 16:26 UTC, merged